name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build 
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Check Code Format
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: -- --check

      - name: Tests
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

      - name: Examples
        uses: actions-rs/cargo@v1.0.3
        env:
          RUST_LOG: "trace"
        with:
          command: run
          args: --all-features --example print-instructions
